### ISSUE TITLE
Support for javascript step definitions

### ISSUE THREAD

**Issue by vldmr-bus** [cucumber/language-server#58] opened 2022-07-12 13:27 UTC
Currently the language server support step definitions only in these 5 languages: typescript, java, c_sharp, php, ruby. Cucumber does support javascript with file extensions '.js' and '.mjs'. Please consider adding support.

**Comment by aslakhellesoy** [comment] 2022-07-14 13:57
Duplicate of https://github.com/cucumber/language-service/issues/42

Please consider submitting a pull request for that issue.

**Closed by aslakhellesoy** 2022-07-14 13:57 UTC
